#DO NOT put real credentials in this file. It is tracked on github and we don't want our key in public
#Use this file as a template and put your real sendgrid credentials in config/application.yml which is safely ignored by git

sendgrid_smtp_username : "apikey"
sendgrid_smtp_password : "put our sendgrid key here"
sendgrid_smtp_port : "587" #port 25 is blocked on most residential ISP's, so use alternate SMTP port
